Test
randor8/wijkagent-groep4-ICT.SE.KBS.V19 pull request #54
Opened 2019-12-13 13:17 UTC by jjtiessen

Will merge 23_filtermenu into master.

2019-12-13 14:44 UTC, randor8 reviewed
Schermontwerp moet bijgewerkt worden ook de omschrijving hierbij.
vull de userstory aan met extra details in fo.
static.......WHY! volgens mij moet je hier dan een singleton gebruiken toch?

2019-12-16 09:50 UTC, jjtiessen commented
> Schermontwerp moet bijgewerkt worden ook de omschrijving hierbij.
> vull de userstory aan met extra details in fo.
> static.......WHY! volgens mij moet je hier dan een singleton gebruiken toch?

Ik neem aan dat je de FilterList bedoelt. Ben het met je eens dat momenteel het niet helemaal klopt. Hij is niet volledig static of singleton. Ik zou alsnog kiezen voor een static klasse omdat ik geen instanties van FilterList wil ondersteunen. De CategoryFilterCollection daarintegen moet wel een singleton zijn omdat hij een interface moet implementeren en als object gebruikt wordt in FilterList.

2019-12-16 10:07 UTC, randor8 requested changes
delicten overzicht mist een scroll bar als filters volledig zijn uitgeklapt

2019-12-16 10:10 UTC, jjtiessen commented
> delicten overzicht mist een scroll bar als filters volledig zijn uitgeklapt

Dat is waar ook, ga ik oplossen

2019-12-16 15:17 UTC, randor8 approved these changes

2019-12-16 15:18 UTC, merged