27 getuigen aanmelden
randor8/wijkagent-groep4-ICT.SE.KBS.V19 pull request #75
Opened 2019-12-23 09:49 UTC by SteviosSDR

Voor het testen moet je eerst je database updaten door de informatie van de online database exporteren.

2019-12-23 10:42 UTC, sbmf21 approved these changes

2019-12-27 07:32 UTC, randor8 commented on WPFWijkagent/WPFWijkagent/AskForWitnessWindow.xaml.cs
> +            }
heb nog nooit zoon grote else statement gezien met maar een operatie

2019-12-27 07:33 UTC, randor8 commented on WPFWijkagent/WPFWijkagent/AskForWitnessWindow.xaml.cs
> +            _window = window;
waarvoor is dezez?

2019-12-27 07:34 UTC, randor8 commented on WPFWijkagent/WPFWijkagent/DelictDialog.xaml.cs
> +            _MainWindow = window;
waaarom mainwindow

2019-12-27 07:34 UTC, randor8 commented on WPFWijkagent/WPFWijkagent/DelictDialog.xaml.cs
> +        }
verwijderen

2019-12-27 07:38 UTC, randor8 commented on WPFWijkagent/WPFWijkagent/DelictDialogController.cs
> +        /// <param name="offenceListItems"></param>
weg

2019-12-27 07:39 UTC, randor8 commented on WPFWijkagent/WPFWijkagent/DelictDialogController.cs
> +        /// <param name="offence"></param>
aanvullen met nieuwe attributen

2019-12-27 07:40 UTC, randor8 commented on WPFWijkagent/WPFWijkagent/MainWindow.xaml.cs
> +        DelictDialog social;
public?

2019-12-27 07:45 UTC, randor8 commented on WPFWijkagent/WPFWijkagent/DelictDialog.xaml.cs
> +            WitnessController witnessController = new WitnessController(_offence, _MainWindow);
WTF is dit je maakt een controller en die maakt een window?? mischien hier gewoon het dialoog maken en die de controller laten initialiseren

2019-12-27 07:48 UTC, randor8 commented on WPFWijkagent/WPFWijkagent/MainWindow.xaml.cs
> +            social = new DelictDialog(pin,
is social wel de goede naam? delictDialog mischien

2019-12-27 07:50 UTC, randor8 commented on WPFWijkagent/WPFWijkagent/MainWindow.xaml.cs
> +            {
waarom niet :
} else 
{

2019-12-27 07:51 UTC, randor8 commented on WPFWijkagent/WPFWijkagent/MainWindow.xaml.cs
> +            }
Dit mag dus niet hier he..... moet in de socialmediamessagcontroller architectuur schennis!!

2019-12-27 07:55 UTC, randor8 commented on WPFWijkagent/WPFWijkagent/Scraper.cs
> +            if(OnlyHastag == false)
```suggestion
            if(!OnlyHastag)
```

2019-12-27 07:58 UTC, randor8 commented on WPFWijkagent/WPFWijkagent/Scraper.cs
> +        private void SetSocialMediaMessage(ITweet tweet, int Type = 0)
waarom noem je hem niet gewoon media type voor onsistency

2019-12-27 08:02 UTC, randor8 commented on WPFWijkagent/WPFWijkagent/Scraper.cs
> +        public void UpdateSocialMediaMessages(int Type = 0)
MediaType....
```suggestion
        public void UpdateSocialMediaMessages(int Mediatype= 0)
```

2019-12-27 08:04 UTC, randor8 commented on WPFWijkagent/WPFWijkagent/WitnessController.cs
> +            witnessWindow = new AskForWitnessWindow(this, window);
steven: eerst het scherm dan de controller niet andersom en die mainwindow is ook niet nodig.

2019-12-27 08:06 UTC, randor8 commented on WPFWijkagent/WPFWijkagent/WitnessController.cs
> +            if(rows.Count > 0)
mag niet... hier weg en in de socialmediamessagecontroller zetten

2019-12-27 08:27 UTC, randor8 requested changes
Beste Steven,

Ik had gehoopt dat je onze architectuur wel begreep maar als ik dit zo zie snap je het nog niet helemaal. Als er dingen zijn die je onlogisch vind, te moeilijk vind, of niet snapt moet je dit zelf aangeven! 
Veel van de fouten die ik zie zullen de werking niet tegengaan maar dit gaat meer om et niveau dat van ons verwacht word. Ik hoop dat je begrijpt dat ik je hiermee wil helpen.
even kort:
1. aantal inconcistenties met naamgeving voor wpf elementen en  optioneel social media type->mediatype etc
2. aantal social,offence,sendmessage controller methoden die je in je scherm controller hebt staan.
3. aantal scherm dingen die je in je controllers hebt staan...
4. aantal slordigheids fouten zoals overdereve veel witruimte, vergeten comments bij methoden.
5.*merge met test moet nog even gedaan worden heb ik nog niet hierin terug gezien namenlijk.

2019-12-27 08:27 UTC, randor8 commented on WPFWijkagent/WPFWijkagent/WitnessController.cs
> +            WitnessScraper.UpdateSocialMediaMessages(1);
een aantal dingen hier:
we werken in oop dus alle functionaliteit is onderschijden van elkaar. jij doet hier 3 dingen:

1. tweet publishen en verversen van tweets (die tweede scraper had hierbij waarschijnlijk niet gehoeven als je de search parameters na initializatie nog kon aanpassen.)
2. updaten van offence (dit moet in de offence controller)
3. toevoegen van sendmessage(hiervoor moet een apparte controller "sendmessagecontroller" of een methode bij social media message alleen klopt dit niet met onze architectuur....)

2019-12-27 08:27 UTC, randor8 commented on WPFWijkagent/WijkagentModels/SocialMediaMessage.cs
> +        public int Type { get; set; }
media type?

2019-12-27 11:36 UTC, randor8 commented on WPFWijkagent/WPFWijkagent/DelictDialogController.cs
>          public DelictDialogController()
kan deze niet weg?

2019-12-27 11:49 UTC, randor8 reviewed
nog een aantal kleine dingen waarvan ik niet wist of je ze over het hoofd had gezien, verder moet je bij die controllers even in je achterhoofd houden wat het gene is dat je toevoegt en of update een update voor offence moet bij de offencecontroller en een select van de sendmessage hoort bij die controller.

Het is lastig gezien deze tabel veel te maken heeft met de offences maar die scheiding is cruciaal!

2019-12-27 11:49 UTC, randor8 commented on WPFWijkagent/WPFWijkagent/AskForWitnessWindow.xaml.cs
>          private MainWindow _window { get; set; }
deze kan nog weg

2019-12-27 11:49 UTC, randor8 commented on WPFWijkagent/WPFWijkagent/WitnessController.cs
> +        private SendMessageController SendMessageController = new SendMessageController();
maak er _varname gezien ze private zijn

2019-12-27 11:49 UTC, randor8 commented on WPFWijkagent/WPFWijkagent/database/SendMessageController.cs
> +        public void UpdateSendMessages(Offence offence, String message)
.. SetSendMessage(...
gezien hij insert en een bericht opslaat niet meerdere

2019-12-27 11:49 UTC, randor8 commented on WPFWijkagent/WPFWijkagent/database/SocialMediaMessageController.cs
> +        }
deze gaat over de sendmessage dus mag ook in die controller ;)

2019-12-27 11:49 UTC, randor8 commented on WPFWijkagent/WPFWijkagent/database/SocialMediaMessageController.cs
> +        }
gaat over offence dus mag bij offence controller

2019-12-31 13:19 UTC, sbmf21 reviewed
Ik heb een opmerking toegevoegd maar daar hoef je niet per se iets mee te doen.
Ik vind het opzich verder prima zou maar moedig je nog wel even aan om nog naar een aantal opmerkingen van Randy te kijken.

2019-12-31 13:19 UTC, sbmf21 commented on WPFWijkagent/WPFWijkagent/AskForWitnessWindow.xaml.cs
> +}
Deze functie kan veel simpeler. De twee if functies kunnen met && in één zodat je ook maar één else statement nodig hebt aangezien ze toch allebij exact hetzelfde doen

2020-01-06 13:54 UTC, SteviosSDR commented on WPFWijkagent/WPFWijkagent/AskForWitnessWindow.xaml.cs
> +            }
Hoe bedoel je? het zijn 2 verschillende error messages.

2020-01-06 13:58 UTC, SteviosSDR commented on WPFWijkagent/WPFWijkagent/AskForWitnessWindow.xaml.cs
> +            _window = window;
window is er uitgehaald

2020-01-06 13:58 UTC, SteviosSDR commented on WPFWijkagent/WPFWijkagent/DelictDialog.xaml.cs
> +        }
gedaan

2020-01-06 13:59 UTC, SteviosSDR commented on WPFWijkagent/WPFWijkagent/DelictDialogController.cs
> +        /// <param name="offenceListItems"></param>
gedaan

2020-01-27 10:01 UTC, closed without merging